name: Test Noml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git clone https://github.com/GenericProgrammer1234/Noml
      - run: export PYTHONPATH="./Noml:$PYTHONPATH"
      - run: alias noml="python ./Noml/app.py"
      - run: noml
