name: Test Noml

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: curl https://raw.githubusercontent.com/GenericProgrammer1234/Noml/main/install.sh | bash
